# Generated by Django 4.2.4 on 2023-09-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Time')),
                ('log_status', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=50, null=True, verbose_name='Status')),
                ('log_server_response', models.TextField(blank=True, null=True, verbose_name='Server response')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='MailingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(verbose_name='Send time')),
                ('period', models.SmallIntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], null=True, verbose_name='Frequency')),
                ('mail_status', models.SmallIntegerField(choices=[(1, 'Finished'), (2, 'Created'), (3, 'Runs')], default=2, verbose_name='Status')),
                ('next_time_run', models.DateField(default=None, null=True, verbose_name='Next time run')),
                ('mail_subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('mail_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_campaign.client', verbose_name='Clients')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
