# Generated by Django 4.2.4 on 2023-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingcampaign',
            name='mail_clients',
        ),
        migrations.AddField(
            model_name='mailingcampaign',
            name='mail_clients',
            field=models.ManyToManyField(null=True, to='email_campaign.client', verbose_name='Clients'),
        ),
    ]
