# Generated by Django 4.2.4 on 2023-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaign', '0004_alter_mailingcampaign_mail_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcampaign',
            name='mail_clients',
            field=models.ManyToManyField(to='email_campaign.client', verbose_name='Clients'),
        ),
    ]
